version: '3'
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: ft_postgres
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./.data:/var/lib/postgresql/data
    ports:
      - 9577:5432